### ISSUE TITLE
Recognizer for string literals — an odd side effect

### ISSUE THREAD

**Issue by ruv** [forthy42/gforth#25]
Gforth 0.7.9_20200618

Input:
```
'|' parse "test passed"| forth-recognizer recognize .s
```

Output:
```
*the terminal*:1:24: error: Undefined word
'|' parse "test passed">>>|<<< forth-recognizer recognize .s
Backtrace:
kernel/int.fs:572:10                     0 $7F92D3400CA0 throw
```

**Comment by ruv** [comment]
This issue is fixed by the commit [903ae890](https://github.com/forthy42/gforth/commit/903ae890fe0c1a747b0510914b20d00b1c406ca2) on 2024-09-28.

Update: see also another [comment](https://github.com/ForthHub/fep-recognizer/issues/7#issuecomment-682239947) on this topic.

**Comment by ebblake** [comment]
Still buggy in a different manner in the latest Gforth 0.7.9_20250723:
```
'!' parse "test passed"! rec-string execute type cr  
*the terminal*:1:24: error: Invalid memory address
'!' parse "test passed">>>!<<< rec-string execute type cr 
```

You may have fixed things so that rec-string no longer moves >IN, but if scan-translate-string is allowed to rewind >IN within the same input line, it can attempt to process the delimiter of a former parse as a standalone word.  I would much rather see:
```
'!' parse "split ! rec-string execute string" type cr
```
produce the output `split string`, which is possible only if scan-translate-string cannot rewind >IN more than one character beyond its current position in the input buffer at the time it is finally executed.

**Comment by ruv** [comment]
The 2024-09-28 commit [903ae890](https://github.com/forthy42/gforth/commit/903ae890fe0c1a747b0510914b20d00b1c406ca2) fixed a bug in recognizing the beginning of a string literal.

But translation (interpretation or compilation) of a string literal is still incorrect.

The following command:
```forth
'|' parse "test passed"| rec-forth ?found cr .( ### interpreting the recognized string literal: )  execute .s cr type 
```

produces this output:
```
### interpreting the recognized string literal: 
*the terminal*:1:24: error: Undefined word
'|' parse "test passed">>>|<<< rec-forth ?found cr .( ### interpreting the recognized string literal: )  execute .s cr type
```

The root of this problem is that the string literal translator reads the input source (and changes the read position) when this is unnecessary since the string parameter contains not a string literal head, but a full string literal.

In my implementation, I return a **character string** translator `tt-slit` (instead of a **string literal tail** translator `tt-slit-parsing`) in such a case, see [string-literal-via-recognizer-v5](https://gist.github.com/ruv/67134d5eb0493969520f77d3f89f85d5#file-file-01-string-literal-via-recognizer-v5-fth-L20):
```forth
: quot ( -- sd.quot ) s\" \"" ;

: recognize-string ( sd.lexeme -- sd tt.slit|tt.slit-parsing | 0 )
  quot match-head 0= if 2drop 0 exit then quot match-tail if ['] tt-slit exit then
  2dup quot contains if 2drop 0 exit then \ fail if '"' is found in the middle of the string
  ['] tt-slit-parsing
;
```

Another solution is to check the input string parameter for the trailing `"` in the _string literal tail translator._

**Comment by ruv** [comment]
> Another solution is to check the input string parameter for the trailing `"` in the _string literal tail translator._

I implemented this in #60.

@ebblake [wrote](https://github.com/forthy42/gforth/issues/25#issuecomment-3214419989):
> ```forth
> '!' parse "split ! rec-string execute string" type cr
> ```
>
> produce the output `split string`, which is possible only if scan-translate-string cannot rewind `>IN` more than one character beyond its current position in the input buffer at the time it is finally executed.
> 

I like this option.  Though I have not implemented it yet, my current [implementation](https://gist.github.com/ruv/67134d5eb0493969520f77d3f89f85d5#file-file-01-string-literal-via-recognizer-v5-fth-L7) throws an exception if the head of a string literal does not end at the beginning of the parsing area.

Implementing this option in Gforth requires more work to upgrade the [word `\"-parse`](https://github.com/forthy42/gforth/blob/02928a5cba711b6ae8604b1722105c85df10f26a/quotes.fs#L119).
